apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAbqZ2xFAbb/5MX702Kfy5Ke5L14jEJk9U8V1QKodlhSrZWni5UfBxdP/Xtw2QV2GzKXyD5Zub42veKAp3mCAvEedTjRdU1/ZCeNzIKcWCyj+NLveoFAkmHEcnKWHrIgi/Lpx2XTDl5h0qasXL9hPRRfQ3wWvHhEWCpFrMoxZ+j93iFdxgKhDNdkOpp+d5MSrNpF8NP7Sy2LyCZvwwhzfBazFUI9NiQOawzVZTh3RNZoFL/eljVeEcpHQCo0RwzYB+2n/YaLG5Nt9dRfOnFuCbMYbOshfDwgumWgD2AUWqo2nvkpoJAeVwNYb8EL5SofJuWu9lUoVwcgS7v0Z/zG7ERXHWODiWR35s+LtpPGXJjYq2P6Kv1kx9LQWDYFuz8yHGlcJoaWwecgUN8fWXYp8VQ5eTNgl8UzYoIVC/uYa/wbf48SEUzi9QZhD065Zp+t+C25DwTNYcTGjwvc6rwOkxRpCgSr2dyXJyOtQWDRQHe2B4SfP6V5fVAPgNXux6Vl9pKz2YMsw8nWyn1LmOr7DK0n0y9LNrGE+7dnJovvoa/mbuEosoWrcSY5xaBmoXFoFurH95ubR6uiFfNjwEcfICE2nV9tgvpB1MFJxvB8yRu8OT5NsWiF9X1+ZTyCjkzZ257CzqVjRh69+r+qFoLyLXYxz3pUkZvVA8UuqKQzy0SgvwRpvz/YWkPSqg45Uf5ZhzmSJxbIdMziA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

