apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgC2tyV0PKJeFItI7aKWiqS1N0kd05J7D3xcst4AAOD2VtavL6bn9UUPpTHLBdg+/9ZqMrBZQR/qJvAZJ1fpRLRB+dT17stF7Kq1ctfN7jUP7KIIrKTmBxdXp+zuex8byyfxSAlrQf0IqReWUBOVjQeg2EhLJBMFjvT3PJ4NRCfVU62juhR4AL/JlgWGL+RlkxaaMYFaOvOfI5Grk4B1OHn1LDxUBKU9n37jsH8dY2a+0/7KvVUYNjTHir94x1/9od9FctVaywag8eUXIoZd4UTdhLxoF37/HCnyS1J7DW+7yQXhDvYqXJ4LO5BEpu3EGSXFVqtzZ14rqobzfO1sDOWNFvVR1Aae8zhXygj+rJB6FsiCWxf5yaZoMS0Zrix+T1n9ka0Db1umWm7OTdAJBLajRMuxjGwDdQu56GQlpnUd7ADUpumGTTep7ZJNOGdyQhlmtbFrLuNkqPMcOjDvAo0anVyqDIHGMcXqWmH1ZdD0n4pCG/jdIfBuvbGByLi0zoSBAwEPLUa+K3tdT/jIjdjcAPB0/q+uXNgM0N78miaeVBqx5B+WQ9D9zHZt9CycUro4jRXIoXSNItGmQcjOg+vSy+S3/NTcez9o1HzIDPWfcY1Cq4ChjSJ//DBEIWtKEnYJ0MS9DBcgvCFaetUTDkWSkxN5bzlwkrSrnFJtUgVh8e5Mb2CPI+jjegvynuKsVTaxOoo+jGXqYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

