apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "278"
  name: sterlingtoolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sterlingtoolkit
  template:
    metadata:
      labels:
        app: sterlingtoolkit
    spec:
      containers:
      - name: sterlingtoolkit
        image: quay.io/hollisc/sterlingtoolkit:1.0.6
        command: ["/bin/bash", "-ce", "cp /temp/db2jcc4.jar /var/nfs-data/resources/ && mkdir -p /var/nfs-data/resources/dbdrivers && mkdir -p /var/nfs-data/resources/pcm && chmod 777 /var/nfs-data/resources/pcm & chmod 777 /var/nfs-data/resources/dbdrivers && cp /temp/db2jcc4.jar /var/nfs-data/resources/dbdrivers  && cp /temp/db2jcc4.jar /var/nfs-data/resources/pcm && tail -f /dev/null"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/nfs-data/resources
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: ibm-pem-resources-pvc
