apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    DB_PASSWORD: AgClPMaGhug2GvIJTegLuImV/BZCZTI56x9YRKR25JSBmZqzGC05UMNAB7sacWak8vt890NK1ZOop09ITjdCTfeDpQn9ElcYFeBvTYKc60lJcgKadJi/RjK7MRzyku1gTj+OYS1fHKn8/jyixUJAzMhGGlZRtrCByrEhUtazRuV8y7V/Dp0WycSllsTzlqaaxyRHe0lxFuvdkgn5tCPVSEgKcwf1qjcCoomjsjqCLFRIDWyoi9rURF20BWVl+8aotKVTCc4oXGba38Zjh6p2FdelAU9iHe8hdiF02pA+dFyh6NXLlwYwvo6Jx8Kjqkktdv3fdsAYNTcNs2oQ5XBfAvSw9D7E7BGllqleNE6MCdTB9sj6kx24WhlCnh93qUrMP7kxO70BdBp5NeFZJfcgQbyRn2EUkOCmqMnBhZOgxNA1v0aR+K/UnHj4pn9Uc9cJjZtqnl53cGQ7JS2N/G22t7y8hu0pHAYg0THiCcL3w8swL8GWqnaEZMwqcgkLGQSCKYR0WNfRu+TdBw05ES97c5i/KLwrIzT0Z+kYgckEU/o80GkAsXyPUd58xipGwjXvipXQ4uMJNh4EhGmTjD/Vq5zb6fJakKDb8RWHZ9+zoP4M7pnnVMIQnJwidIJ6iHTCeUp9hggsOEOa0Nr25K85nveKCAQlmPjETk//8WgflRX+P1aJLJLai1oidBQ5GiR68WBWTQnVpknORg==
    DB_USER: AgCI9gaQdkvXgWsElnrdkGSnI+CJbbDAXCcTZ3+dCJarcjg4HABK0yf6XIOV8/HDZa3sk4pl4QqJjPTozJSDW3JklgIOS0bCIVb0oAGHa9WxM4IGvlKw8EirK41466FFJrvar8ZcaIF8XQwRLYHZRCkCCes2pbCVbCCbdeA7qAiD6e6q+OdSzfKdt+rq+y2/ICBgE8BywolPe9Xxc2QzgTTP4WBi/pguJi3QfiGf9GWLuW2iKp1y3wyk+LfyR3z0eIxcLqLS7N/+a+uG0jF10jUOlEHn+8nvLGNrmNGK+tcufEvjVFzUZOQ9wH9Mp8pzqvgRgVk6nUtIefj79EBaw7fhn4ftHsW+/gR4P1v2p2nPp7S59tysvt3LFmIFU+27jNLyAkuRd0jEEIyeFb6/DvM80T0uRR3OxPpjXtUt5VqandKlw2GnpyCwaHHMFxLVqsj9Ty0uBKsVCp4Re+V/WEEHZYVX/Euztv/xgzj2xB6Zwo34LUgwP1AAe2rdMRboxc7GPGeXvbtU2dn1iwPLBGIvj1I8iwkcOYGbvxkyd1Xi4JWIqYllVD59A4LZbSBi/IWLo09WEPOr5CyQEIRc2PpeED/vuitK7wcHgdN+RXAegd+N1Lag4P49eYXCsjhsDL4HmVb5DTKnajSdw9zPhjBL40urYaETpiqpyLbYB7FLGXv0VmQKLu1xNdzLxM1mRVCzQz/MgsfrtQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-nonprod
    type: Opaque

