apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    DB_PASSWORD: AgAJWIJ0eAtd2AObRhPC4nTvJc+PHtry3cwAgmhzhnhK4UbZL4+ld0ivgToCD5rCvPB7SmpgMtRoyhqqWH9+z1/IswlQPST6cNTC+T0vnfuhYmoTokyaiDhBpdv/o8q330YOWaMaqvi+oVjWHGPA7C1pdJx03k8DG3IA4SHrNv+h65nbukprBhLi2tjhVzULtZA6/USDEYaYm+FPalKQay4Bd6xi2AsNzD9EFqxrF1ZnZVkP2YtjoOhu2NOfoxY64j71lr0FDwf+J1XA8InbfsvgujwMXUcURYcpJyiFxC4EjDQ3gUXXrqFHBDWYgjLi1qehQvLtqv4G2eUaMOnO5zRBO4tpugoBzl7ldN4+VxgYK1Pjne/Oqk1aVBs9ssO1CQEuKK35cvqYRt+ZVzV+n7TT7b0oYobHr/Z3cq87xPqY57qDVl8fsbFqb5esAIZZ6Hfe0vkmlHr3ZvJyEB8IM9IrrxFG8sd4H4We3AQpFdEkcdi9QIKJ07ctlJ0FrVnh3g9GzKaafmro1utlwzng4Wu6wx4vIMGOCdCFn26UvuP6taX0Txcy40+LOlMKFz0+0zGes4MFnLx4JOHlWfrbkYuwj0LR/9lQOo5faEQtsBBX8P+uoOmNNqfO7GESnusQ+KjiZ4mcrbvreyJdqA3/70zQvkjnXh4wkXgu88bUsM8QS85fqzUsAq2xIq+WkpvvNXwQIdl0ZemDZw==
    DB_USER: AgCJ7IGbqoYL1Dgi1IGpP+7N2JmHU4RNbwB1JUKWUPbzLIBg07wMHuc3lswlVkPMO4uZjFihneiPZzJg1/z/3ZeTwqIF2Y9JmVbaYeWIl5JGOjbSOfmav7YKAMVQOFJx0erjTIGTlQtBbDVydE6eu4782Vcx3PQBJt0iVxDT11gSAg0Eroqmh8gd/ihERDTEdSwfYNqpRRKR1S5Gvp4+qCFj523HAHcYlUJEOSK6/oos3oSyK51pcKcwSfQxSwsuccwSjKCdDUGAq8AmzoOQgfqOcGD/dWY0YbwMDYo7uvFS3lohD2joUmQWb05/PdmKA5o8xYA4iOykp5398a1FfiL/Iog5UdnmYW9zwKMwELytGDL9tKV0KRaOqlYze6NbbdqfKPVa0BUMnUlqbXlCVg2RzaNWgH4IBPvVjlX8CMzcj4R3dDp6x0ibv5eIqVrRrkaH4SrcFIZjqcr2S8Wlhi58DyhWiHi2xOso0mdFRTsmKwQqb0C2khjuTw/ERL1x1uF0n0PWo+pep8SVZ4+TNHOPllKYzkiTBPnwihTIpMgdEUY+qkFUaLhECnqot5wyf/TVe3B+D5iYWl8w86RCWvv7hFoku+qCS3E7/Pttm0Q6OpMtaQUHM/cR9AMYUIFYFJ/djSsfY9ZW+4b5fafbN3nHsquzsb2IU+fq7kddvPVgirajANK3lWFGtR7hqebp36L+JVMPERF1mQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-nonprod
    type: Opaque

