#!/usr/bin/env bash
# Set enviroment variables
# Declaring IBM SFG PROD

PEM_NS="pem"
NS="pem"
B2BI_PROD="b2bi-prod"
B2BI_NONPROD="b2bi-nonprod"
PEM_VERSION="6.2.0.2"
RWX_STORAGECLASS=${RWX_STORAGECLASS:-"ibmc-file-gold"}

# Create Kubernetes yaml
( echo "cat <<EOF" ; cat ibm-pem-overrides-values.yaml_template ;) | \
SFG_REPO=${SFG_REPO} \
SFG_TAG=${SFG_TAG} \
SFG_PULLSECRECT=${SFG_PULLSECRECT} \
APP_RESOURCES_PVC_ENABLED=${APP_RESOURCES_PVC_ENABLED} \
APP_DOCUMENTS_PVC_ENABLED=${APP_DOCUMENTS_PVC_ENABLED} \
DATASETUP_ENABLED=${DATASETUP_ENABLED} \
DBHOST=${DBHOST} \
DBPORT=${DBPORT} \
DBDATA=${DBDATA} \
DBCREATESCHEMA=${DBCREATESCHEMA} \
JMSHOST=${JMSHOST} \
JMSPORT=${JMSPORT} \
JMSCONNECTIONNAMELIST=${JMSCONNECTIONNAMELIST} \
JSMCHANNEL=${JSMCHANNEL} \
INGRESS_INTERNAL_HOST_ASI=${INGRESS_INTERNAL_HOST_ASI} \
INGRESS_INTERNAL_HOST_AC=${INGRESS_INTERNAL_HOST_AC} \
INGRESS_INTERNAL_HOST_API=${INGRESS_INTERNAL_HOST_API} \
PURGE_IMG_REPO=${PURGE_IMG_REPO} \
PURGE_IMG_TAG=${PURGE_IMG_TAG} \
RWX_STORAGECLASS=${RWX_STORAGECLASS} \
PURGE_PULLSECRET=${PURGE_PULLSECRET} \
sh > values.yaml
